### ISSUE TITLE
Invalid max_acceptances type in createInvitation API

### ISSUE THREAD

**Issue by anthonyherveHCS** [IBM-Blockchain-Identity/openssi-websdk#22]
Hello, 
It seems that the **max_acceptances** parameter in **createInvitation** API must be a number.
`@param {number} max_acceptances The maximum number of times this invitation can be accepted.  Default -1 (unlimited)`

But the code throws a TypeError if its type is not a boolean
```
if (max_acceptances && typeof max_acceptances !== 'boolean')
			throw new TypeError('Invalid invitation max acceptances');
```
Thanks

**Comment by joevolleyball** [comment]
fixed the type test inside createInvitation.  Added fix and testing for invitation with non-default values.
